Add Update User Route
captis/backend pull request #122
Opened 2021-12-17 19:02 UTC by tckthecreator

## What this PR introduces?

Add Update User Route

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [x] My code produces no warnings or errors in the console
- [x] Tests for the changes have been added / updated
- [x] Mocks fot the database have been added / updated

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Documentation update
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] CI/CD related changes
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information (Prints, details, etc)

2021-12-20 01:53 UTC, henriqueleite42 requested changes

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/index.ts
> +	usersDomainPatchRoute: patchRoute,
`usersDomainPatchRoute` -> `usersDomainUpdate`

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/update/handler.ts
> +export const patchRoute = makeHandler({
`patchRoute` -> `update`

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/update/service.ts
> +	updateUserRepository: UpdateUserType;
`updateUserRepository` -> `updateRepository`

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/update/controller.ts
> +	const params = await validate(JSON.parse(event.body || "{}"));
Create a function to extract the user id from the authorization header, and add it to the parsed json to be validated

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/update/service.ts
> +	password?: string;
`password`, `email`, and `phone` will have separate routes, so they shouldn't be updated here

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/update/service.ts
> +		statusCode: StatusCodeEnum.SUCCESS,
`SUCCESS` -> `NO_BODY`

2021-12-20 01:53 UTC, henriqueleite42 commented on src/api/users/update/validate.ts
> +		password: yup.string().notRequired().min(1).max(20),
`password`, `email`, and `phone` will have separate routes, so they shouldn't be updated here

2021-12-20 01:53 UTC, henriqueleite42 commented on src/database/repositories/users/update/types.ts
> +	password?: string;
`password`, `email`, and `phone` will have separate routes, so they shouldn't be updated here

2021-12-20 01:53 UTC, henriqueleite42 commented on src/tests/api/users/update/service.spec.ts
> +		it("should return status code 200", async () => {
`200` -> `204`

2021-12-20 01:53 UTC, henriqueleite42 commented on src/tests/api/users/update/service.spec.ts
> +						password: validPassword,
`password`, `email`, and `phone` will have separate routes, so they shouldn't be updated here

2021-12-20 01:53 UTC, henriqueleite42 commented on src/tests/api/users/update/service.spec.ts
> +				statusCode: StatusCodeEnum.SUCCESS,
`SUCCESS` -> `NO_BODY`

2021-12-20 01:53 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +	});
Add testes for undefined params,for invalid types and invalid params

2021-12-20 01:53 UTC, henriqueleite42 requested changes

2021-12-20 01:53 UTC, henriqueleite42 commented on src/database/repositories/users/update/index.ts
> +export const makeUpdateUser =
makeUpdate

2021-12-20 02:44 UTC, henriqueleite42 requested changes

2021-12-20 02:44 UTC, henriqueleite42 commented on src/database/repositories/users/update/index.ts
> +		if (columnsToUpdate.length === 0) throw new Error("No params puted");
```ts
// eslint-disable-next-line @typescript-eslint/no-magic-numbers
if (columnsToUpdate.length === 0) {
  throw new CustomError("No columns to update", StatusCodeEnum.BAD_REQUEST);
}

2021-12-20 16:51 UTC, henriqueleite42 requested changes
Set the PR as ready for review

2021-12-20 16:51 UTC, henriqueleite42 commented on src/api/users/update/controller.ts
> +	const getId = (): string => {
Transform this in an util (getUserData), and extract user id from the `sub` property of the JWT payload (payload.sub)

Ref:
- https://www.npmjs.com/package/jsonwebtoken#jwtdecodetoken--options
- - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-id-token.html

2021-12-20 16:51 UTC, henriqueleite42 commented on src/api/users/update/controller.ts
> +	const params = await validate(JSON.parse(`[${getId()}, ${event.body}]`));
This should be an object, not an array, and the id should be merged with the passed json, ex: `validate({...JSON.parse(...), id: id})`

2021-12-20 16:51 UTC, henriqueleite42 commented on src/api/users/update/service.ts
> +	username?: string;
Hmmm, actually, the username also will be updated separately, because it needs some extra validation.
Remove it from here, please.

2021-12-20 16:51 UTC, henriqueleite42 commented on src/api/users/update/validate.ts
> +		displayName: yup.string().notRequired().min(1).max(25),
`.max(40)`

2021-12-20 16:51 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +	it("should throw an error if the id has the wrong type", async () => {
It should be inside a describe

2021-12-20 16:51 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +	it("should throw an error if the displayName has the wrong type", async () => {
It should be inside a describe

2021-12-20 16:51 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +	it("should throw an error if the bio has the wrong type", async () => {
It should be inside a describe

2021-12-20 16:51 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +});
Add tests to check what happens when undefined params are passed

2021-12-20 19:37 UTC, tckthecreator commented on src/api/users/update/controller.ts
> +	const getId = (): string => {
the function must get only the ID?

2021-12-20 19:52 UTC, tckthecreator commented on src/api/users/update/controller.ts
> +	const getId = (): string => {
I receive the token from the authorizations header?

2021-12-21 23:50 UTC, henriqueleite42 requested changes

2021-12-21 23:50 UTC, henriqueleite42 commented on src/api/users/update/controller.ts
> +	const id = getUserData(event.headers);
`const { id }`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/api/users/update/controller.ts
> +	const params = await validate({ ...JSON.parse(`${event.body}`), id });
`JSON.parse(event.body || "{}")`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/database/repositories/users/update/index.ts
> +		if (username) {
Remove

2021-12-21 23:50 UTC, henriqueleite42 commented on src/database/repositories/users/update/types.ts
> +	username?: string;
Remove

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/service.spec.ts
> +	});
Add test cases:
- Only with the displayName
- Only with the bio

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +	const invalidId = "1";
Remove these variables. Invalid values should be inside the test cases.

2021-12-21 23:50 UTC, henriqueleite42 commented on src/api/users/update/validate.ts
> +		id: yup.number().required().min(1),
`id` is a `string`, also, add validation `.uuid()`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/api/users/update/service.ts
> +	id: number;
`id: string;`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/database/repositories/users/update/types.ts
> +	id: number;
`id: string;`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +		it("should throw an error if the id has the wrong type", async () => {
Type validation should be inside another describe:
https://github.com/captis/backend/pull/129/files#diff-aba83a1ad4aa1d278ac50ca97aa518bc87a893d8134639a65509fbd90bc6707b

Follow the same naming patterns of describes.

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +					id: invalidId as any,
Use the value directly instead

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +				'id must be a `number` type, but the final value was: `"1"`.',
`string`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +		it("should throw an error if the displayName has the wrong type", async () => {
Type validation should be inside another describe:
https://github.com/captis/backend/pull/129/files#diff-aba83a1ad4aa1d278ac50ca97aa518bc87a893d8134639a65509fbd90bc6707b

Follow the same naming patterns of describes.

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +		it("should throw an error if the bio has the wrong type", async () => {
Type validation should be inside another describe:
https://github.com/captis/backend/pull/129/files#diff-aba83a1ad4aa1d278ac50ca97aa518bc87a893d8134639a65509fbd90bc6707b

Follow the same naming patterns of describes.

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +					id: undefined as any,
Use an empty object instead

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +					displayName: undefined as any,
```
{
	id: validId,
  bio: validBio,
}
```

2021-12-21 23:50 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +					bio: undefined as any,
```
{
	id: validId,
  displayName: validDisplayName,
}
```

2021-12-21 23:50 UTC, henriqueleite42 commented on src/utils/get-user-data.ts
> +	if (authorization !== undefined) {
`if (authorization) {`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/utils/get-user-data.ts
> +		if (payload !== null) {
`if (payload) {`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/utils/get-user-data.ts
> +			return payload.sub;
`return payload`

2021-12-21 23:50 UTC, henriqueleite42 commented on src/utils/get-user-data.ts
> +	const authorization = headers.authorization;
`const { authorization } = headers;`

2021-12-22 04:59 UTC, tckthecreator commented on src/api/users/update/validate.ts
> +		id: yup.number().required().min(1),
In the user migration, id is a BIGSERIAL, so i cant test

2021-12-22 05:03 UTC, tckthecreator commented on src/api/users/update/validate.ts
> +		id: yup.number().required().min(1),
I cant test on pg4admin*

2021-12-23 00:49 UTC, henriqueleite42 approved these changes

2021-12-23 00:49 UTC, henriqueleite42 commented on src/tests/api/users/update/service.spec.ts
> +	describe("Update Successfully", () => {
This should be `Success`

2021-12-23 00:49 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +		it("should return validated when suplied params", async () => {
`"should return validated params"`

2021-12-23 00:49 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +		it("should throw an error if the id has the wrong type", async () => {
`"should throw an error with invalid id type"`

2021-12-23 00:49 UTC, henriqueleite42 commented on src/tests/api/users/update/validate.spec.ts
> +		it("should return an error if id is undefined", async () => {
This test should not exist

2021-12-23 01:41 UTC, merged